# Configs - Notify administrator

labels:
  - name: 'PR'
    PR:
    Pull requets:
        body: |
          你好!管理员.@Mint-XiaoTian @ze8611 @Miax0724
          目前这个PR没有配置
          请尽快解决.
          
  - name: 'Issues'
    Issues:
      issue:
        body: |
          你好!管理员.@Mint-XiaoTian @ze8611 @Miax0724
          目前这个issues没有配置
          请尽快解决.
