name: PR

on: # 满足什么条件触发
  pull_request_target:
types:
    - Open

jobs:
  read-file:
	runs-on: ubuntu-latest
	outputs:
	  require-result: ${{ steps.contributors.outputs.content}}
	steps:
	  - name:
		uses: actions/checkout@v1
	  - name: Read contributors.json
		id: contributors
		uses: juliangruber/read-file-action@v1
		with:
		  path: ./contributors.json

  check-permission:
    runs-on: ubuntu-latest
	outputs:
	  require-result: ${{ steps.checkUser.outputs.require-result }}
	steps:
	  - uses: actions-cool/check-user-permission@v2
		id: checkUser 
		with:
		  require: 'write'

  check_merged:
	runs-on: ubuntu-latest
	needs: [read-file, check-permission]
	if: needs.check-permission.outputs.require-result == 'false' && contains(fromJSON(needs.read-file.outputs.require-result), github.actor) == false && github.event.pull_request.Open == true # 发送消息需要满足的条件
	steps:
	  - uses: actions-cool/maintain-one-comment@v3
		with:
		  body: [Hi! 欢迎提交PR 此分支已接收 等待管理员Merged]
